### ISSUE TITLE
Slow Response in HA when deCONZ is Running

### ISSUE THREAD

**Issue by dlindnegm** [dresden-elektronik/deconz-rest-plugin#3826]
## Describe the question or issue you are having
I've been running the default ZHA zigbee integration on a Rpi4 for about 5 months with about 20 sensors, lights and switches. Everything has worked perfectly until I decided to try installing the official deCONZ add-on. As soon as I start the add-on my zigbee network slows to a crawl. Lights and switches either don't turn on/off at all, or they have 2-5 second delays. The status of the lights and switches in HA often are either greyed out or show the incorrect state. As soon as I stop the add-on everything returns to normal.

## Environment
 - Host system: Raspberry Pi 4
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26680700
 - deCONZ version:  2.07.00
 - Device:  ConBee II 
 - Do you use an USB extension cable: yes 
 - Is there any other USB or serial devices connected to the host system? Yes If so: Which? Zooz Z-Wave Plus S2 USB Stick ZST10

## deCONZ Logs
11:39:42:043 wait reconnect 11 seconds
11:39:43:043 wait reconnect 10 seconds
11:39:44:043 wait reconnect 9 seconds
11:39:45:043 failed to reconnect to network try=6
11:39:45:044 wait reconnect 8 seconds
11:39:46:043 wait reconnect 7 seconds
11:39:47:043 wait reconnect 6 seconds
11:39:48:043 wait reconnect 5 seconds
11:39:49:043 wait reconnect 4 seconds
11:39:50:043 failed to reconnect to network try=7
11:39:50:044 wait reconnect 3 seconds
11:39:51:043 wait reconnect 2 seconds
11:39:51:093 dev /dev/ttyAMA0
11:39:52:043 wait reconnect 1 seconds
11:39:52:089 dev /dev/ttyAMA0
11:39:52:090 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2217285-if00 / serialno: , ConBee II
11:39:52:112 device disconnected reason: 4, index: 0
11:39:53:043 wait reconnect 15 seconds
11:39:53:098 dev /dev/ttyAMA0
11:39:53:099 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2217285-if00 / serialno: , ConBee II
11:39:54:043 wait reconnect 14 seconds
11:39:55:043 failed to reconnect to network try=8
11:39:55:044 wait reconnect 13 seconds
11:39:56:043 wait reconnect 12 seconds
11:39:57:043 wait reconnect 11 seconds
11:39:58:043 wait reconnect 10 seconds
11:39:59:043 wait reconnect 9 seconds
11:40:00:043 failed to reconnect to network try=9
11:40:00:044 wait reconnect 8 seconds
11:40:01:043 wait reconnect 7 seconds
11:40:01:088 dev /dev/ttyAMA0
11:40:02:043 wait reconnect 6 seconds
11:40:03:043 wait reconnect 5 seconds
11:40:04:043 wait reconnect 4 seconds
11:40:05:043 failed to reconnect to network try=10
11:40:05:043 wait reconnect 3 seconds
11:40:06:043 wait reconnect 2 seconds
11:40:07:043 wait reconnect 1 seconds
11:40:07:099 dev /dev/ttyAMA0
11:40:07:099 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2217285-if00 / serialno: , ConBee II
11:40:07:158 device disconnected reason: 4, index: 0
11:40:08:043 wait reconnect 15 seconds
11:40:08:099 dev /dev/ttyAMA0
11:40:08:099 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2217285-if00 / serialno: , ConBee II
11:40:09:043 wait reconnect 14 seconds
11:40:10:043 reconnect network failed, try later
11:40:10:043 wait reconnect 13 seconds
11:40:10:543 start reconnect to network
11:40:11:043 wait reconnect 12 seconds
11:40:11:088 dev /dev/ttyAMA0
11:40:12:042 wait reconnect 11 seconds
11:40:13:043 wait reconnect 10 seconds
11:40:14:043 wait reconnect 9 seconds
11:40:15:043 wait reconnect 8 seconds
11:40:15:793 failed to reconnect to network try=1
11:40:16:043 wait reconnect 7 seconds
11:40:17:043 wait reconnect 6 seconds
11:40:18:043 wait reconnect 5 seconds
11:40:19:043 wait reconnect 4 seconds
11:40:20:043 wait reconnect 3 seconds
11:40:21:043 failed to reconnect to network try=2
11:40:21:044 wait reconnect 2 seconds
11:40:21:098 dev /dev/ttyAMA0
11:40:22:043 wait reconnect 1 seconds
11:40:22:089 dev /dev/ttyAMA0
11:40:22:089 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2217285-if00 / serialno: , ConBee II
11:40:22:102 device disconnected reason: 4, index: 0
11:40:23:043 wait reconnect 15 seconds
11:40:23:089 dev /dev/ttyAMA0
11:40:23:090 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2217285-if00 / serialno: , ConBee II
11:40:24:043 wait reconnect 14 seconds
11:40:25:043 wait reconnect 13 seconds
11:40:26:043 failed to reconnect to network try=3
11:40:26:044 wait reconnect 12 seconds
11:40:27:043 wait reconnect 11 seconds
11:40:28:043 wait reconnect 10 seconds
11:40:29:043 wait reconnect 9 seconds
11:40:30:043 wait reconnect 8 seconds
11:40:31:044 failed to reconnect to network try=4
11:40:31:045 wait reconnect 7 seconds
11:40:31:089 dev /dev/ttyAMA0
11:40:32:043 wait reconnect 6 seconds
11:40:33:043 wait reconnect 5 seconds
11:40:34:043 wait reconnect 4 seconds
11:40:35:043 wait reconnect 3 seconds
11:40:36:043 failed to reconnect to network try=5
11:40:36:043 wait reconnect 2 seconds
11:40:37:043 wait reconnect 1 seconds
11:40:37:090 dev /dev/ttyAMA0
11:40:37:090 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2217285-if00 / serialno: , ConBee II
11:40:37:111 device disconnected reason: 4, index: 0
11:40:38:043 wait reconnect 15 seconds
11:40:38:102 dev /dev/ttyAMA0
11:40:38:103 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2217285-if00 / serialno: , ConBee II
11:40:39:043 wait reconnect 14 seconds
11:40:40:043 wait reconnect 13 seconds
11:40:41:043 failed to reconnect to network tr172.30.32.2 - - [07/Dec/2020:18:40:50 +0000] "GET /novnc/websockify HTTP/1.1" 101 69796 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
localhost - - [07/Dec/2020 11:40:50] 127.0.0.1:5900: Client closed connection
localhost - - [07/Dec/2020 11:40:50] 127.0.0.1:5900: Closed target
Ignoring interrupted syscall

1:22:57:894 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 0, 2, x'11408e4911593d0000003d0000', 1607365377 FROM devices WHERE mac = 'e2:0d:b9:ff:fe:03:c7:8a'
11:22:58:054 DB UPDATE device_descriptors SET data = x'0a5ec00001020700000010040003000500060008000200001900', timestamp = 1607365378 WHERE device_id = (SELECT id FROM devices WHERE mac = 'e2:0d:b9:ff:fe:03:c7:8a') AND endpoint = 10 AND type = 4
11:22:58:055 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 10, 4, x'0a5ec00001020700000010040003000500060008000200001900', 1607365378 FROM devices WHERE mac = 'e2:0d:b9:ff:fe:03:c7:8a'
11:22:58:159 ZDP discovery done in 200 ms11:22:59:973 APS-DATA.indication from unknown node 0x000D6F000E339C12
11:23:03:543 device state timeout ignored in state 3
11:23:04:290 ZCL attribute report 0x000D6F0005077149 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000
11:23:08:046 saved node state in 1 ms
11:23:08:615 sync() in 568 ms
11:23:10:434 device state timeout ignored in state 3
11:23:11:931 APS-DATA.indication from unknown node 0x000D6F000E339C12
11:23:18:043 device state timeout ignored in state 3
11:23:20:549 device state timeout ignored in state 3
11:23:23:543 device state timeout ignored in state 3
11:23:24:060 Current channel 15
11:23:24:071 Device TTL 7082 s flags: 0x7
11:23:28:886 device state timeout ignored in state 3
11:23:34:622 DB UPDATE device_descriptors SET data = x'11408e4911593d0000003d0000', timestamp = 1607365414 WHERE device_id = (SELECT id FROM devices WHERE mac = 'e2:0d:b9:ff:fe:0a:a4:7b') AND endpoint = 0 AND type = 2
11:23:34:623 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 0, 2, x'11408e4911593d0000003d0000', 1607365414 FROM devices WHERE mac = 'e2:0d:b9:ff:fe:0a:a4:7b'
11:23:34:833 DB UPDATE device_descriptors SET data = x'0a5ec00001020700000010040003000500060008000200001900', timestamp = 1607365414 WHERE device_id = (SELECT id FROM devices WHERE mac = 'e2:0d:b9:ff:fe:0a:a4:7b') AND endpoint = 10 AND type = 4
11:23:34:834 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 10, 4, x'0a5ec00001020700000010040003000500060008000200001900', 1607365414 FROM devices WHERE mac = 'e2:0d:b9:ff:fe:0a:a4:7b'
11:23:34:943 ZDP discovery done in 229 ms11:23:35:874 APS-DATA.indication from unknown node 0x000D6F000E339C12
11:23:39:543 device state timeout ignored in state 3
11:23:45:045 saved node state in 1 ms
11:23:45:389 sync() in 343 ms
11:23:45:851 APS-DATA.indication from unknown node 0x000D6F000E339C12
11:23:47:916 device state timeout ignored in state 3
11:23:50:543 device state timeout ignored in state 3
11:23:52:876 APS-DATA.indication from unknown node 0x000D6F000E339C12
11:23:55:703 DB UPDATE device_descriptors SET data = x'11408e4911593d0000003d0000', timestamp = 1607365435 WHERE device_id = (SELECT id FROM devices WHERE mac = 'e2:0d:b9:ff:fe:03:c7:40') AND endpoint = 0 AND type = 2
11:23:55:705 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 0, 2, x'11408e4911593d0000003d0000', 1607365435 FROM devices WHERE mac = 'e2:0d:b9:ff:fe:03:c7:40'
127.0.0.1: new handler Process
localhost - - [07/Dec/2020 11:26:13] "GET //vnc_lite.html?scale=yes HTTP/1.1" 200 -
11:23:55:867 DB UPDATE device_descriptors SET data = x'0a5ec00001020700000010040003000500060008000200001900',172.30.32.2 - - [07/Dec/2020:18:26:13 +0000] "GET /novnc/vnc_lite.html?scale=yes HTTP/1.1" 200 3396 "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
Ignoring interrupted syscall
127.0.0.1: new handler Process
localhost - - [07/Dec/2020 11:26:14] "GET //websockify HTTP/1.1" 101 -
localhost - - [07/Dec/2020 11:26:14] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
localhost - - [07/Dec/2020 11:26:14] 127.0.0.1: Version hybi-13, base64: 'False'
localhost - - [07/Dec/2020 11:26:14] 127.0.0.1: Path: '//websockify'
localhost - - [07/Dec/2020 11:26:14] connecting to: 127.0.0.1:5900
localhost - - [07/Dec/2020 11:26:34] 127.0.0.1:5900: Client closed connection
localhost - - [07/Dec/2020 11:26:34] 127.0.0.1:5900: Closed target
172.30.32.2 - - [07/Dec/2020:18:26:39 +0000] "GET /novnc/websockify HTTP/1.1" 101 120495 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
Ignoring interrupted syscall
127.0.0.1: new handler Process
localhost - - [07/Dec/2020 11:26:46] "GET //websockify HTTP/1.1" 101 -
localhost - - [07/Dec/2020 11:26:46] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
localhost - - [07/Dec/2020 11:26:46] 127.0.0.1: Version hybi-13, base64: 'False'
localhost - - [07/Dec/2020 11:26:46] 127.0.0.1: Path: '//websockify'
localhost - - [07/Dec/2020 11:26:46] connecting to: 127.0.0.1:5900
localhost - - [07/Dec/2020 11:27:01] 127.0.0.1:5900: Client closed connection
localhost - - [07/Dec/2020 11:27:01] 127.0.0.1:5900: Closed target
2020/12/07 18:27:01 [info] 968#968: *4 recv() failed (104: Connection reset by peer) while proxying upgraded connection, client: 172.30.32.2, server: _, request: "GET /novnc/websockify HTTP/1.1", upstream: "http://127.0.0.1:5901//websockify", host: "192.168.0.115:8123"
172.30.32.2 - - [07/Dec/2020:18:27:01 +0000] "GET /novnc/websockify HTTP/1.1" 101 107747 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
Ignoring interrupted syscall
2020/12/07 18:27:08 [info] 968#968: *6 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 172.30.32.2, server: _, request: "GET /pwa/index.html HTTP/1.1", upstream: "http://127.0.0.1:40850/pwa/index.html", host: "192.168.0.115:8123", referrer: "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html"
172.30.32.2 - - [07/Dec/2020:18:27:08 +0000] "GET /pwa/index.html HTTP/1.1" 499 0 "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
2020/12/07 18:27:09 [info] 968#968: *8 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 172.30.32.2, server: _, request: "GET /pwa/index.html HTTP/1.1", upstream: "http://127.0.0.1:40850/pwa/index.html", host: "192.168.0.115:8123", referrer: "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html"
172.30.32.2 - - [07/Dec/2020:18:27:09 +0000] "GET /pwa/index.html HTTP/1.1" 499 0 "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
2020/12/07 18:27:11 [info] 968#968: *10 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 172.30.32.2, server: _, request: "GET /pwa/index.html HTTP/1.1", upstream: "http://127.0.0.1:40850/pwa/index.html", host: "192.168.0.115:8123", referrer: "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html"
172.30.32.2 - - [07/Dec/2020:18:27:11 +0000] "GET /pwa/index.html HTTP/1.1" 499 0 "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
127.0.0.1: new handler Process
2020/12/07 18:28:19 [info] 968#968: *12 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 172.30.32.2, server: _, request: "GET /pwa/index.html HTTP/1.1", upstream: "http://127.0.0.1:40850/pwa/index.html", host: "192.168.0.115:8123", referrer: "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html"
172.30.32.2 - - [07/Dec/2020:18:28:19 +0000] "GET /pwa/index.html HTTP/1.1" 499 0 "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
2020/12/07 18:28:19 [info] 968#968: *14 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while sending request to upstream, client: 172.30.32.2, server: _, request: "GET /novnc/vnc_lite.html?scale=yes HTTP/1.1", upstream: "http://127.0.0.1:5901//vnc_lite.html?scale=yes", host: "192.168.0.115:8123", referrer: "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html"
172.30.32.2 - - [07/Dec/2020:18:28:19 +0000] "GET /novnc/vnc_lite.html?scale=yes HTTP/1.1" 499 0 "http://192.168.0.115:8123/api/hassio_ingress/A9smEEXjM19iakY_yRwryrin_Jhm6DnMfeWUM9DDbmo/ingress.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
localhost - - [07/Dec/2020 11:28:19] "GET //vnc_lite.html?scale=yes HTTP/1.1" 200 -
handler exception: [Errno 32] Broken pipe
exception
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 933, in top_new_client
client = self.do_handshake(startsock, address)
File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 863, in do_handshake
self.RequestHandlerClass(retsock, address, self)
File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 114, in init
SimpleHTTPRequestHandler.init(self, req, addr, server)
File "/usr/lib/python2.7/SocketServer.py", line 655, in init
self.handle()
File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 581, in handle
SimpleHTTPRequestHandler.handle(self)
File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
self.handle_one_request()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
method()
File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 547, in do_GET
SimpleHTTPRequestHandler.do_GET(self)
File "/usr/lib/python2.7/SimpleHTTPServer.py", line 45, in do_GET
f = self.send_head()
File "/usr/lib/python2.7/SimpleHTTPServer.py", line 99, in send_head
self.send_response(200)
File "/usr/lib/python2.7/BaseHTTPServer.py", line 406, in send_response
self.send_header('Server', self.version_string())
File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
self.wfile.write("%s: %s\r\n" % (keyword, value))
File "/usr/lib/python2.7/socket.py", line 328, in write
self.flush()
File "/usr/lib/python2.7/socket.py", line 307, in flush
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
Ignoring interrupted syscall

## Additional context
Occasionally I can get into the Phoscon or deCONZ app via the HA GUI, but most times they are unresponsive. When I can connect with the deCONZ app it usually won't connect to the ConBee. Once or twice I have been able to connect and see the network mesh with all of my devices. As soon as I stop the Add-on all of my zigbee devices start working again.

Log Errors from HA:
No response to 'Command.aps_data_request' command with seq id '0x85'
11:28:25 AM – /usr/local/lib/python3.8/site-packages/zigpy_deconz/api.py (WARNING) - message first occurred at 11:20:47 AM and shows up 70 times
Unexpected transmit confirm for request id 132, Status: TXStatus.SUCCESS
11:26:04 AM – /usr/local/lib/python3.8/site-packages/zigpy_deconz/zigbee/application.py (WARNING) - message first occurred at 11:22:53 AM and shows up 3 times
No watchdog response
11:25:32 AM – /usr/local/lib/python3.8/site-packages/zigpy_deconz/zigbee/application.py (WARNING)
Updating zha sensor took longer than the scheduled update interval 0:00:30
11:25:16 AM – Sensor (WARNING) - message first occurred at 11:24:46 AM and shows up 2 times

**Comment by dlindnegm** [comment]
Looks like you can't run both ZHA and deCONZ on the same device! Thanks Robert S.!
