### ISSUE TITLE
Deconz - HA - Aqara FP1 - Devicemode 'leftright' not setable

### ISSUE THREAD

**Issue by marsteff** [dresden-elektronik/deconz-rest-plugin#6649]
## Describe the bug
Hello,

i´ve bought the new Aqara FP1 Sensor and want to use it with the Deconz Integration.
Everything work well, but when i try to set the Device Mode from undirected to leftright i get the error you see in this post.

I´ve opened a ticket on Home Assistant Side and they mean, they spoke to you that it is an error on your side:
https://github.com/home-assistant/core/issues/84769

## Environment
 Raspberry Pi 4 with HomeAssistant OS

## deCONZ Logs
Logger: homeassistant.components.websocket_api.http.connection
Source: components/deconz/select.py:82
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 25. Dezember 2022 um 19:00:04 (2 occurrences)
Last logged: 12:40:14

[2526116544] {'address': '/sensors/24/config/devicemode', 'description': 'Could not set attribute', 'type': 608}
[2502492464] {'address': '/sensors/24/config/devicemode', 'description': 'Could not set attribute', 'type': 608}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 56, in async_select_option
    await entity.async_select_option(option)
  File "/usr/src/homeassistant/homeassistant/components/deconz/select.py", line 82, in async_select_option
    await self.gateway.api.sensors.presence.set_config(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/interfaces/sensors.py", line 367, in set_config
    return await self.gateway.request_with_retry(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 142, in request_with_retry
    return await self.request(method, path, json)
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 167, in request
    response: dict[str, Any] = await self._request(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 194, in _request
    _raise_on_error(response)
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 225, in _raise_on_error
    raise_error(data["error"])
  File "/usr/local/lib/python3.10/site-packages/pydeconz/errors.py", line 80, in raise_error
    raise pydeconzException(error)
pydeconz.errors.pydeconzException: {'address': '/sensors/24/config/devicemode', 'description': 'Could not set attribute', 'type': 608}
Additional information
No response

**Comment by SwoopX** [comment]
That's indeed caused by a regression on deconz side. I'll see that I add a PR for this somewhere today so it gets added asap. In the meantime, you can make the setting via deconz GUI.
